using UnityEngine;
using UnityEditor;
using System.IO;
using System.Collections.Generic;
using System.Linq;

/// <summary>
/// Tools > Rename GameObjects to Engine Part Names
///
/// Renames GameObject nodes in an engine prefab or scene instance to match the 
/// clean, technical engine part names generated by the Groq AI tool (from PartData / EnginePart).
/// Only modifies GameObject node names in the hierarchy — EnginePart.partName and PartData remain untouched.
/// </summary>
public class RenameGameObjectsToPartNamesTool : EditorWindow
{
    private GameObject _engineModel;
    private string     _partsFolderOverride = "";
    private bool       _autoNumberDuplicates = false;
    private bool       _useZeroPadding = true;

    private Vector2    _scrollPos;
    private List<RenamePreviewItem> _previewItems = new List<RenamePreviewItem>();

    public class RenamePreviewItem
    {
        public GameObject TargetObject;
        public string     CurrentName;
        public string     ProposedName;
        public string     Source;
        public bool       WillChange => CurrentName != ProposedName && !string.IsNullOrEmpty(ProposedName);
    }

    [MenuItem("Tools/Rename GameObjects to Engine Part Names")]
    public static void Open()
    {
        var window = GetWindow<RenameGameObjectsToPartNamesTool>("Rename to Part Names");
        window.minSize = new Vector2(520, 560);
        window.Show();
    }

    void OnEnable()
    {
        if (Selection.activeGameObject != null)
        {
            _engineModel = Selection.activeGameObject;
            RefreshPreview();
        }
    }

    void OnSelectionChange()
    {
        if (Selection.activeGameObject != null && _engineModel != Selection.activeGameObject)
        {
            _engineModel = Selection.activeGameObject;
            RefreshPreview();
            Repaint();
        }
    }

    void OnGUI()
    {
        EditorGUILayout.Space(8);
        GUILayout.Label("Rename GameObjects to Groq Engine Part Names", EditorStyles.boldLabel);
        EditorGUILayout.LabelField("Renames 3D mesh GameObjects ONLY. Leaves EnginePart.partName and PartData untouched.", EditorStyles.miniLabel);
        EditorGUILayout.Space(6);

        // ── Target Model ──────────────────────────────────────────────────────
        EditorGUI.BeginChangeCheck();
        _engineModel = (GameObject)EditorGUILayout.ObjectField(
            "Target Model / Prefab", _engineModel, typeof(GameObject), true);
        if (EditorGUI.EndChangeCheck())
        {
            RefreshPreview();
        }

        if (_engineModel == null)
        {
            EditorGUILayout.HelpBox("Drag an Engine Prefab or Hierarchy GameObject here to preview and rename its GameObject node names.", MessageType.Info);
            return;
        }

        // ── Parts Folder Override ─────────────────────────────────────────────
        EditorGUILayout.BeginHorizontal();
        string newFolder = EditorGUILayout.TextField("Parts Folder Override", _partsFolderOverride);
        if (newFolder != _partsFolderOverride)
        {
            _partsFolderOverride = newFolder;
            RefreshPreview();
        }
        if (GUILayout.Button("Browse", GUILayout.Width(60)))
        {
            string path = EditorUtility.OpenFolderPanel("Select Parts Folder containing PartData", "Assets/ScriptableObjects/Data/Engines", "");
            if (!string.IsNullOrEmpty(path))
            {
                if (path.StartsWith(Application.dataPath))
                    _partsFolderOverride = "Assets" + path.Substring(Application.dataPath.Length);
                else
                    _partsFolderOverride = path;
                RefreshPreview();
            }
        }
        EditorGUILayout.EndHorizontal();

        EditorGUILayout.Space(6);

        // ── Settings ──────────────────────────────────────────────────────────
        GUILayout.Label("Renaming Options", EditorStyles.boldLabel);
        EditorGUI.BeginChangeCheck();
        _autoNumberDuplicates = EditorGUILayout.Toggle(new GUIContent("Auto-Number Duplicates", "Appends 01, 02 suffix to identical GameObject names (e.g. Turbine Blade 01, Turbine Blade 02)"), _autoNumberDuplicates);
        if (_autoNumberDuplicates)
        {
            EditorGUI.indentLevel++;
            _useZeroPadding = EditorGUILayout.Toggle("Use Zero Padding (01, 02)", _useZeroPadding);
            EditorGUI.indentLevel--;
        }
        if (EditorGUI.EndChangeCheck())
        {
            RefreshPreview();
        }

        EditorGUILayout.Space(8);

        // ── Preview Header & Summary ──────────────────────────────────────────
        int totalParts = _previewItems.Count;
        int toChange = _previewItems.Count(p => p.WillChange);

        EditorGUILayout.BeginHorizontal();
        GUILayout.Label($"Preview ({toChange}/{totalParts} GameObjects will be renamed)", EditorStyles.boldLabel);
        if (GUILayout.Button("🔄 Refresh", GUILayout.Width(80)))
        {
            RefreshPreview();
        }
        EditorGUILayout.EndHorizontal();

        // ── Preview List Table ────────────────────────────────────────────────
        _scrollPos = EditorGUILayout.BeginScrollView(_scrollPos, GUI.skin.box, GUILayout.Height(280));
        if (_previewItems.Count == 0)
        {
            EditorGUILayout.HelpBox("No EnginePart components found on this model. Run 'Tools > Engine Part Setup' first.", MessageType.Warning);
        }
        else
        {
            EditorGUILayout.BeginHorizontal(EditorStyles.toolbar);
            GUILayout.Label("Current GameObject Name", EditorStyles.miniBoldLabel, GUILayout.Width(170));
            GUILayout.Label("→", EditorStyles.miniBoldLabel, GUILayout.Width(20));
            GUILayout.Label("New GameObject Name", EditorStyles.miniBoldLabel, GUILayout.Width(190));
            GUILayout.Label("Source", EditorStyles.miniBoldLabel, GUILayout.Width(80));
            EditorGUILayout.EndHorizontal();

            foreach (var item in _previewItems)
            {
                Color origBg = GUI.backgroundColor;
                if (item.WillChange)
                    GUI.backgroundColor = new Color(0.7f, 1f, 0.7f, 1f);
                else
                    GUI.backgroundColor = new Color(0.9f, 0.9f, 0.9f, 0.5f);

                EditorGUILayout.BeginHorizontal("box");
                GUI.backgroundColor = origBg;

                GUILayout.Label(item.CurrentName, EditorStyles.label, GUILayout.Width(170));
                GUILayout.Label("→", EditorStyles.boldLabel, GUILayout.Width(20));

                if (item.WillChange)
                    GUILayout.Label(item.ProposedName, EditorStyles.boldLabel, GUILayout.Width(190));
                else
                    GUILayout.Label(string.IsNullOrEmpty(item.ProposedName) ? "(No Name Found)" : item.ProposedName + " (Matches)", EditorStyles.miniLabel, GUILayout.Width(190));

                GUILayout.Label(item.Source, EditorStyles.miniLabel, GUILayout.Width(80));

                EditorGUILayout.EndHorizontal();
            }
        }
        EditorGUILayout.EndScrollView();

        EditorGUILayout.Space(10);

        // ── Execute Button ───────────────────────────────────────────────────
        GUI.enabled = _engineModel != null && toChange > 0;
        Color btnColor = GUI.enabled ? new Color(0.2f, 0.6f, 0.3f) : Color.gray;
        Color origBtn = GUI.backgroundColor;
        GUI.backgroundColor = btnColor;

        if (GUILayout.Button($"⚡ RENAME {toChange} GAMEOBJECTS NOW", GUILayout.Height(42)))
        {
            ApplyRenaming();
        }
        GUI.backgroundColor = origBtn;
        GUI.enabled = true;

        EditorGUILayout.Space(4);
    }

    // ─────────────────────────────────────────────────────────────────────────

    private void RefreshPreview()
    {
        _previewItems.Clear();
        if (_engineModel == null) return;

        // Locate Parts folder
        string partsFolder = !string.IsNullOrEmpty(_partsFolderOverride) && Directory.Exists(_partsFolderOverride)
            ? _partsFolderOverride
            : FindPartsFolderForModel(_engineModel);

        var partDataDict = new Dictionary<string, PartData>();
        if (!string.IsNullOrEmpty(partsFolder) && Directory.Exists(partsFolder))
        {
            var guids = AssetDatabase.FindAssets("t:PartData", new[] { partsFolder });
            foreach (var g in guids)
            {
                var pd = AssetDatabase.LoadAssetAtPath<PartData>(AssetDatabase.GUIDToAssetPath(g));
                if (pd != null)
                {
                    partDataDict[pd.name] = pd;
                    string norm = Normalize(pd.name);
                    if (!partDataDict.ContainsKey(norm)) partDataDict[norm] = pd;
                }
            }
        }

        // Collect all EnginePart components on the model
        EnginePart[] parts = _engineModel.GetComponentsInChildren<EnginePart>(true);

        var tempItems = new List<RenamePreviewItem>();
        foreach (var ep in parts)
        {
            if (ep == null) continue;

            string proposedName = "";
            string source = "None";

            // Source 1: PartData asset assigned to EnginePart component
            if (ep.partData != null && !string.IsNullOrEmpty(ep.partData.partName))
            {
                proposedName = ep.partData.partName;
                source = "PartData";
            }
            // Source 2: partName field directly on EnginePart component
            else if (!string.IsNullOrEmpty(ep.partName) && ep.partName != ep.gameObject.name)
            {
                proposedName = ep.partName;
                source = "EnginePart";
            }
            // Source 3: PartData lookup by original GameObject name
            else
            {
                string normGoName = Normalize(ep.gameObject.name);
                if (partDataDict.TryGetValue(ep.gameObject.name, out PartData pd) || partDataDict.TryGetValue(normGoName, out pd))
                {
                    if (pd != null && !string.IsNullOrEmpty(pd.partName))
                    {
                        proposedName = pd.partName;
                        source = "PartData Match";
                    }
                }
            }

            tempItems.Add(new RenamePreviewItem
            {
                TargetObject = ep.gameObject,
                CurrentName  = ep.gameObject.name,
                ProposedName = proposedName,
                Source       = source
            });
        }

        // Second pass: handle duplicate auto-numbering on GameObjects if enabled
        if (_autoNumberDuplicates)
        {
            var baseNameGroups = tempItems.GroupBy(item => item.ProposedName).ToList();
            foreach (var group in baseNameGroups)
            {
                if (string.IsNullOrEmpty(group.Key)) continue;

                var list = group.ToList();
                if (list.Count > 1)
                {
                    for (int i = 0; i < list.Count; i++)
                    {
                        int number = i + 1;
                        string fmt = _useZeroPadding ? (list.Count >= 10 ? "D2" : "D2") : "D";
                        list[i].ProposedName = $"{group.Key} {number.ToString(fmt)}";
                    }
                }
            }
        }

        _previewItems = tempItems;
    }

    private void ApplyRenaming()
    {
        if (_engineModel == null || _previewItems.Count == 0) return;

        bool isPrefab = PrefabUtility.IsPartOfPrefabAsset(_engineModel);
        string prefabPath = isPrefab ? AssetDatabase.GetAssetPath(_engineModel) : "";

        int count = 0;

        if (isPrefab && !string.IsNullOrEmpty(prefabPath))
        {
            // Prefab mode: edit inside EditPrefabContentsScope
            using (var scope = new PrefabUtility.EditPrefabContentsScope(prefabPath))
            {
                var root = scope.prefabContentsRoot;
                var engineParts = root.GetComponentsInChildren<EnginePart>(true);

                foreach (var ep in engineParts)
                {
                    if (ep == null) continue;

                    var preview = _previewItems.FirstOrDefault(p => p.TargetObject != null && p.TargetObject.name == ep.gameObject.name);
                    if (preview == null && ep.partData != null)
                    {
                        preview = _previewItems.FirstOrDefault(p => p.ProposedName == ep.partData.partName || (p.TargetObject != null && ep.partData.name.Contains(p.CurrentName)));
                    }

                    if (preview != null && preview.WillChange)
                    {
                        // ONLY rename the GameObject itself — leave EnginePart fields and PartData untouched!
                        ep.gameObject.name = preview.ProposedName;
                        count++;
                    }
                }
            }
            AssetDatabase.Refresh();
        }
        else
        {
            // Scene instance mode: use Undo so user can undo in 1 click
            Undo.SetCurrentGroupName("Rename GameObjects to Engine Part Names");
            int groupIndex = Undo.GetCurrentGroup();

            foreach (var item in _previewItems)
            {
                if (item.TargetObject == null || !item.WillChange) continue;

                // ONLY rename the GameObject itself — leave EnginePart fields and PartData untouched!
                Undo.RegisterCompleteObjectUndo(item.TargetObject, "Rename GameObject");
                item.TargetObject.name = item.ProposedName;

                EditorUtility.SetDirty(item.TargetObject);
                count++;
            }

            Undo.CollapseUndoOperations(groupIndex);
        }

        EditorUtility.DisplayDialog(
            "Renaming Complete",
            $"Successfully renamed {count} GameObject nodes to match their Groq engine part names!\n\nNote: PartData and EnginePart.partName fields were left completely untouched.",
            "OK"
        );

        Debug.Log($"[RenameGameObjectsToPartNamesTool] Renamed {count} GameObjects on '{_engineModel.name}'. EnginePart.partName was untouched.");
        RefreshPreview();
    }

    private static string FindPartsFolderForModel(GameObject model)
    {
        string modelName = model.name;
        string modelNorm = Normalize(modelName);

        // Search EngineData assets
        string[] edGuids = AssetDatabase.FindAssets("t:EngineData");
        foreach (var guid in edGuids)
        {
            var ed = AssetDatabase.LoadAssetAtPath<EngineData>(AssetDatabase.GUIDToAssetPath(guid));
            if (ed == null) continue;

            bool match = false;
            if (ed.enginePrefab != null)
                match = AssetDatabase.GetAssetPath(ed.enginePrefab) == AssetDatabase.GetAssetPath(model);

            if (!match && ed.engineName != null)
                match = Normalize(ed.engineName) == modelNorm;

            if (match)
            {
                string edDir = Path.GetDirectoryName(AssetDatabase.GetAssetPath(ed)).Replace("\\", "/");
                string partsPath = edDir + "/Parts";
                if (Directory.Exists(partsPath) || AssetDatabase.IsValidFolder(partsPath)) return partsPath;
            }
        }

        // Search directory names
        string[] allDirs = Directory.GetDirectories("Assets", "Parts", SearchOption.AllDirectories);
        foreach (var dir in allDirs)
        {
            string unityDir = dir.Replace("\\", "/");
            string engineFolder = Path.GetFileName(Path.GetDirectoryName(unityDir));
            if (Normalize(engineFolder) == modelNorm || Normalize(engineFolder).Contains(modelNorm) || modelNorm.Contains(Normalize(engineFolder)))
                return unityDir;
        }

        return null;
    }

    private static string Normalize(string s)
    {
        if (string.IsNullOrEmpty(s)) return "";
        return new string(s.Where(char.IsLetterOrDigit).ToArray()).ToLowerInvariant();
    }
}
